name: unittest on push

on:
  push:
    branches:
      - master
      - release

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare the repo
        uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Test
        run: python tests/unittest/test_sum.py
